# Generated by Django 4.1.4 on 2022-12-12 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ace1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('ace2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('ace3', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('ace4', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('horas', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(800)])),
            ],
        ),
    ]
