# Generated by Django 4.1.4 on 2022-12-12 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='horas',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ace1',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Projetos e programas'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ace2',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Cursos e eventos'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ace3',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Prestação de serviços'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ace4',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Disciplinas extensionista'),
        ),
    ]
